spring:
  application:
    name: discovery-server
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}

eureka:
  username: ${EUREKA_USERNAME:admin}
  password: ${EUREKA_PASSWORD:123456Ax}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://admin:123456Ax@localhost:8761/eureka/

# Avoid some debugging logs at startup
logging:
  level:
    org:
      springframework:
        boot: INFO
        web: INFO
server:
  port: 8761
---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888

