version: '3.9'

services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - postgres_network


  jop-app:
    image: mohumadkhald/jobapp:1.0
    container_name: jobapp
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - postgres_network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge
