apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-1
spec:
  replicas: 2
  selector:
    app: nginx-1
  template:
    metadata:
      name: nginx-1
      labels:
        app: nginx-1
    spec:
      containers:
        - name: nginx-1
          image: nginx:1.14.2
          ports:
            - containerPort: 80
